# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20170206_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.BucketlistItem'),
            preserve_default=False,
        ),
    ]
